# A NEW UPDATE MUST BE THIS MANY DAYS OLD
MinimumAge=7
# PREVIOUSLY DOWNLOADED PACKAGES DELETED IF OLDER THAN THIS MANY DAYS
OldUpdates=60
# NETWORK TIMEOUT IN SECONDS (900s = 15m)
NetTimeout=900
# SCRIPT WILL SELF-UPDATE IF SET TO 1
SelfUpdate=1
# BYPASS ALL MINIMUM AGE CHECKS IF SET TO 1 (CAN ALSO BE FORCED VIA -f FLAG)
SkipAgeCheck=0
